// 향료 이름 ↔ 코드 데이터 (fragrance.html, fragrance-check.html, blending.html 공용)
// 코드는 대문자 PB + 두 자리 숫자 형식입니다.
//   note   : 'Top' | 'Middle' | 'Base'  (노트 - 블랜딩 계산기에서 사용)
//   family : 계열(Floral, Citrus 등) - 워크시트 3페이지 표기 기준
// ※ 워크시트에 실린 18종은 표기 그대로, 나머지는 일반 조향 분류를 따랐습니다.
window.FRAGRANCES = [
    { name: '로즈', code: 'PB03', note: 'Middle', family: 'Floral' },
    { name: '무화과', code: 'PB82', note: 'Top', family: 'Fruity' },
    { name: '시더우드', code: 'PB30', note: 'Base', family: 'Woody' },
    { name: '시나몬', code: 'PB11', note: 'Base', family: 'Spicy' },
    { name: '오렌지', code: 'PB20', note: 'Top', family: 'Citrus' },
    { name: '일랑일랑', code: 'PB16', note: 'Middle', family: 'Floral' },
    { name: '자몽', code: 'PB01', note: 'Top', family: 'Citrus' },
    { name: '샌달우드', code: 'PB09', note: 'Base', family: 'Woody' },
    { name: '레몬', code: 'PB02', note: 'Top', family: 'Citrus' },
    { name: '라임', code: 'PB68', note: 'Top', family: 'Citrus' },
    { name: '진저', code: 'PB23', note: 'Top', family: 'Spicy' },
    { name: '자스민', code: 'PB18', note: 'Middle', family: 'Floral' },
    { name: '허니써클', code: 'PB13', note: 'Middle', family: 'Floral' },
    { name: '수선화', code: 'PB28', note: 'Middle', family: 'Floral' },
    { name: '프리지아', code: 'PB05', note: 'Middle', family: 'Floral' },
    { name: '베르가못', code: 'PB10', note: 'Top', family: 'Citrus' },
    { name: '밤부', code: 'PB79', note: 'Middle', family: 'Green' },
    { name: '그린', code: 'PB83', note: 'Middle', family: 'Green' },
    { name: '클라리세이지', code: 'PB35', note: 'Middle', family: 'Herbal' },
    { name: '오션', code: 'PB42', note: 'Middle', family: 'Marine' },
    { name: '민트', code: 'PB39', note: 'Top', family: 'Herbal' },
    { name: '아쿠아', code: 'PB51', note: 'Middle', family: 'Marine' },
    { name: '마린블루', code: 'PB19', note: 'Middle', family: 'Marine' },
    { name: '레더', code: 'PB69', note: 'Base', family: 'Animalic' },
    { name: '블랙커런트', code: 'PB46', note: 'Middle', family: 'Fruity' },
    { name: '머스크', code: 'PB75', note: 'Base', family: 'Musk' },
    { name: '블랙베리', code: 'PB44', note: 'Middle', family: 'Fruity' },
    { name: '바이올렛', code: 'PB41', note: 'Middle', family: 'Floral' },
    { name: '라일락', code: 'PB06', note: 'Middle', family: 'Floral' },
    { name: '아이리스', code: 'PB81', note: 'Middle', family: 'Floral' },
    { name: '라벤더', code: 'PB24', note: 'Middle', family: 'Herbal' },
    { name: '히아신스', code: 'PB64', note: 'Middle', family: 'Floral' },
    { name: '프랑킨센스', code: 'PB80', note: 'Base', family: 'Balsamic' },
    { name: '다마스크로즈', code: 'PB66', note: 'Middle', family: 'Floral' },
    { name: '블랙체리', code: 'PB45', note: 'Middle', family: 'Fruity' },
    { name: '헬리오트핀', code: 'PB62', note: 'Base', family: 'Floral' },
    { name: '피오니', code: 'PB61', note: 'Middle', family: 'Floral' },
    { name: '매그놀리아', code: 'PB76', note: 'Middle', family: 'Floral' },
    { name: '피치복숭아', code: 'PB15', note: 'Middle', family: 'Fruity' },
    { name: '앰버그리스', code: 'PB52', note: 'Base', family: 'Amber' },
    { name: '로즈우드', code: 'PB72', note: 'Base', family: 'Woody' },
    { name: '오렌지 플라워', code: 'PB25', note: 'Middle', family: 'Floral' },
    { name: '타임', code: 'PB33', note: 'Top', family: 'Herbal' },
    { name: '튜베로즈', code: 'PB21', note: 'Middle', family: 'Floral' },
];
